# More than one day of special runs:
# clean the environment
rm(list=ls(all=TRUE))
basepath <- path.expand("~")
setwd(paste0(basepath,"/repositories/cona-arrowtown2019/"))
print(x_now <- as.POSIXct("2020-06-24 18:00:00"))
source("./Special_Run_Daily.R")
rm(list=ls(all=TRUE))
basepath <- path.expand("~")
setwd(paste0(basepath,"/repositories/cona-arrowtown2019/"))
print(x_now <- as.POSIXct("2020-06-25 18:00:00"))
source("./Special_Run_Daily.R")
rm(list=ls(all=TRUE))
basepath <- path.expand("~")
setwd(paste0(basepath,"/repositories/cona-arrowtown2019/"))
print(x_now <- as.POSIXct("2020-06-26 18:00:00"))
source("./Special_Run_Daily.R")
rm(list=ls(all=TRUE))
basepath <- path.expand("~")
setwd(paste0(basepath,"/repositories/cona-arrowtown2019/"))
print(x_now <- as.POSIXct("2020-06-27 18:00:00"))
source("./Special_Run_Daily.R")
rm(list=ls(all=TRUE))
basepath <- path.expand("~")
setwd(paste0(basepath,"/repositories/cona-arrowtown2019/"))
print(x_now <- as.POSIXct("2020-06-28 18:00:00"))
source("./Special_Run_Daily.R")

